version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: rentals-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Rentals
    expose:
      - "3306"

  Rental-app:
    depends_on:
      - mysql
    image: rentals:latest
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: Rentals
