version: '3'

services:
  rentalservice:
    image: mysql:latest
    container_name: rental-application
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Rentals
    expose:
      - "3306"
    volumes:
      - mysql-data:/var/lib/mysql

  Rental-apprental-management:
    depends_on:
      - rentalservice
    image: weneey/rental-with-mysql:latest
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: rentalservice
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: Rentals
      MYSQL_CONNECTION_URL: jdbc:mysql://rentalservice:3306/Rentals

volumes:
  mysql-data:
