version: '3'

services:
  rentalservice:
    image: mysql:latest
    container_name: rental-application
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Rentals
    expose:
      - "3306"

  Rental-apprental-management:
    depends_on:
      - rentalservice
    image: rental-management:latest
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: Rentals
