apiVersion: apps/v1
kind: Deployment
metadata:
  name: rental
  labels:
    app: rental
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rental
  template:
    metadata:
      labels:
        app: rental
    spec:
      containers:
        - name: rental
          image: weneey/rental-with-mysql:latest
          env:
            - name: MYSQL_CONNECTION_URL
              value: jdbc:mysql://mysql:3306/Rentals

            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-map
                  key: MYSQL_USER

            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: MYSQL_PASSWORD

          ports:
            - containerPort: 8080